[build]
  command = "bash -lc 'mkdir -p gradepad/jsScripts && cat > gradepad/jsScripts/firebase-config.js <<EOF\nexport const firebaseConfig = {\n  apiKey: \"$FIREBASE_API_KEY\",\n  authDomain: \"gradepad-improved.firebaseapp.com\",\n  projectId: \"gradepad-improved\",\n  storageBucket: \"gradepad-improved.firebasestorage.app\",\n  messagingSenderId: \"223375674663\",\n  appId: \"1:223375674663:web:6a2c54d972034e1c21ed02\",\n  measurementId: \"G-7T6TTG6XQL\"\n};\nEOF' && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/gradepad/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
