[build]
  command = "npm run build"
  publish = "dist"

# Let actual HTML files be served directly (about.html, support.html, features.html, etc.)
# Only redirect 404s to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/gradepad/index.html"
  status = 404

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
